apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  namespace: devops-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins-admin
      containers:
        - name: jenkins-image
          image: {{ .Values.jenkins.image }}
          imagePullPolicy: "Always"
          resources:
            limits:
              memory: "2Gi"
              cpu: "2000m"
            requests:
              memory: "1Gi"
              cpu: "1000m"
          ports:
            - name: httpport
              containerPort: 80
            - name: jnlpport
              containerPort: 50000
          envFrom:
            - secretRef:
                name: jenkins-secret
          volumeMounts:
            - name: jenkins-data
              mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-data
          persistentVolumeClaim:
            claimName: jenkins-pv-claim
      restartPolicy: Always
