apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "trace.fullname" . }}-pvc
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}
