apiVersion: v1
kind: ConfigMap
metadata: 
  name: glpi-config
  namespace: glpi 
data: 
  GLPI_LANG: {{ .Values.GLPI_LANG }}
  VERSION: {{ .Values.VERSION }}
  GLPI_MARKETPLACE_DIR: {{ .Values.GLPI_MARKETPLACE_DIR }}
  GLPI_VAR_DIR: {{ .Values.GLPI_VAR_DIR }}
  GLPI_DOC_DIR: {{ .Values.GLPI_DOC_DIR }}
  GLPI_CRON_DIR: {{ .Values.GLPI_CRON_DIR }}
  GLPI_DUMP_DIR: {{ .Values.GLPI_DUMP_DIR }}
  GLPI_GRAPH_DIR: {{ .Values.GLPI_GRAPH_DIR }}
  GLPI_LOCK_DIR: {{ .Values.GLPI_LOCK_DIR }}
  GLPI_LOG_DIR: {{ .Values.GLPI_LOG_DIR }}
  GLPI_PICTURE_DIR: {{ .Values.GLPI_PICTURE_DIR }}
  GLPI_PLUGIN_DOC_DIR: {{ .Values.GLPI_PLUGIN_DOC_DIR }}
  GLPI_RSS_DIR:  {{ .Values.GLPI_RSS_DIR }}
  GLPI_SESSION_DIR: {{ .Values.GLPI_SESSION_DIR }}
  GLPI_TMP_DIR: {{ .Values.GLPI_TMP_DIR }}
  GLPI_UPLOAD_DIR: {{ .Values.GLPI_UPLOAD_DIR }}
  GLPI_CACHE_DIR: {{ .Values.GLPI_CACHE_DIR }}
  GLPI_CONFIG_DIR: {{ .Values.GLPI_CONFIG_DIR }}

  MARIADB_HOST: {{ .Values.MARIADB_HOST }}
  MARIADB_PORT: {{ .Values.MARIADB_PORT }}

--- 

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  labels:
    name: nginx-conf
  namespace: glpi 
data:
  default.conf: |-
    server {
        listen 80;
        listen [::]:80;
        
        server_name glpi.localhost;
        
        root /var/www/html/public;
        
        location / {
            try_files $uri /index.php$is_args$args;
        }
        
        location ~ ^/index\.php$ {
            # the following line needs to be adapted, as it changes depending on OS distributions and PHP versions
            fastcgi_pass php-fpm.glpi.svc.cluster.local:9000;
            
            fastcgi_split_path_info ^(.+\.php)(/.*)$;
            include fastcgi_params;
            
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
    }
