apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: glpi-ingress
  namespace: glpi 
  annotations: 
    cert-manager.io/issuer: "letsencrypt-prod"

spec:
  ingressClassName: traefik
  tls: 
  - hosts:
    - {{ .Values.GLPI_HOST }}
    secretName: glpi-tls
  rules:
  - host: {{ .Values.GLPI_HOST }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 80
