replicaCount: 1

image:
  repository:
  tag: latest
  pullPolicy: Always

imagePullSecrets:
  - name: regcred

service:
  type: LoadBalancer
  port: 1989
  additionalPort: 1981

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host:
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: beafowl-tls
      hosts:
        -

persistence:
  enabled: true
  storageClass: openebs-hostpath
  size: 250Gi

rbac:
  create: true
  serviceAccountName: trace-sa

serviceAccount:
  create: true
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

resources: {}
